@baseUrl = http://localhost:3000

@userId=6a101c40b574efcd5768027b

@tripId=6a1d48b7ad4f953a2ee6ed67

@itineraryId=6a2a64d5513abd694e594f03

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTEzZDA4OGY5MWZjMjcwY2M3OTQ3NjAiLCJpYXQiOjE3ODIwMjEwMzUsImV4cCI6MTc4MjEwNzQzNX0.F0AR5QsEH-2RRSiER69YZ3pt5lkVA6oow544r8t9Ggw

@invitationToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlwSWQiOiI2YTFkNDhiN2FkNGY5NTNhMmVlNmVkNjciLCJpYXQiOjE3ODA2NDcxODUsImV4cCI6MTc4MDY1MDc4NX0.PG_BHKEIXqheNAKKVliKGnF8HrYWJ7XCrGwjKpSxeFk

### Create Baggage Data
POST {{baseUrl}}/{{tripId}}/baggages       
//baggage location handlers ko index ma define gareko
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Suit"
}

### Get all bagggages
GET {{baseUrl}}/{{tripId}}/baggages
Authorization: Bearer {{token}}


### Get a specific baggages
GET {{baseUrl}}/{{tripId}}/baggages/6a0017f8db270fbb2fb28397
Authorization: Bearer {{token}}


###update a specific baggage
PATCH {{baseUrl}}/{{tripId}}/baggages/6a0017f8db270fbb2fb28397
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "name": "Jeans",
    "completed": true
}

###Delete a specific baggages
DELETE {{baseUrl}}/{{tripId}}/baggages/6a0017f8db270fbb2fb28397
Authorization: Bearer {{token}}


### Create Itinerary
POST {{baseUrl}}/{{tripId}}/itineraries
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "trip": "{{tripId}}",
    "title": "Day 1 in Pokhara",
    "description": "Arrival, lake walk, and dinner near Lakeside.",
    //"date": "2025-12-15",
    "startDate": "2025-12-15",
    "endDate": "2025-12-20",
    "activities": [
        {
            "name": "Check in at hotel",
            "time": "14:00",
            "notes": [
                "Confirm lake-view room",
                "Ask about breakfast timing"
            ]
        },
        {
            "name": "Walk around Phewa Lake",
            "time": "17:00",
            "notes": [
                "Bring a light jacket"
            ]
        }
    ]
}

### Get all itineraries
GET {{baseUrl}}/{{tripId}}/itineraries
Authorization: Bearer {{token}}

### Get a specific itinerary
GET {{baseUrl}}/{{tripId}}/itineraries/{{itineraryId}}
Authorization: Bearer {{token}}

### Update a specific itinerary
PATCH {{baseUrl}}/{{tripId}}/itineraries/{{itineraryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Day 1 in Pokhara - Lakeside",
    "description": "Arrival, sunset walk, and dinner near Lakeside.",
    "date": "2025-12-15",
    "activities": [
        {
            "name": "Check in at hotel",
            "time": "14:00",
            "notes": [
                "Confirm lake-view room"
            ]
        },
        {
            "name": "Dinner at Lakeside",
            "time": "19:30",
            "notes": [
                "Reserve a table"
            ]
        }
    ]
}

### Delete a specific itinerary
DELETE {{baseUrl}}/{{tripId}}/itineraries/{{itineraryId}}
Authorization: Bearer {{token}}


###create a user 
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Faahhh User",
    "email": "user@test4.com",
    "password": "dsfghjghf"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Get specific user
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

###update a specific user
PATCH  {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Faaaahhhhh",
    "email": "fah@test6.com"
}

###delet a specific user
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

###register a user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test3.com",
    "password": "abcdefgh"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@test3.com",
    "password": "abcdefgh"
}

### create a new trip
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}

### Get all trips
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### Get a trip by id
GET {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### Update trip
PATCH {{baseUrl}}/trips/{{tripId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "budget": {
    "expenses": [
        {
            "name": "taxi",
            "amount": 600
        }
    ]
  }
}

### Delete a trip
DELETE {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### send trip invitation
POST {{baseUrl}}/trips/{{tripId}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "collaboratorEmails": [
        "dass2005nd@gmail.com"
    ]
}

### Accept invite
GET {{baseUrl}}/trips/{{tripId}}/invite/accept?token={{invitationToken}}
Authorization: Bearer {{token}}