@baseUrl = http://localhost:3000

POST {{baseUrl}}/baggages       
//baggage location handlers ko index ma define gareko
Content-Type: application/json

{
    "name": "Suit"
}

### Get all bagggages
GET {{baseUrl}}/baggages

### Get a specific baggages
GET {{baseUrl}}/baggages/6a0017f8db270fbb2fb28397