@baseUrl = http://localhost:3000

@userId=6a101c40b574efcd5768027b

POST {{baseUrl}}/baggages       
//baggage location handlers ko index ma define gareko
Content-Type: application/json

{
    "name": "Suit"
}

### Get all bagggages
GET {{baseUrl}}/baggages

### Get a specific baggages
GET {{baseUrl}}/baggages/6a0017f8db270fbb2fb28397

###update a specific baggage
PATCH {{baseUrl}}/baggages/6a0017f8db270fbb2fb28397
Content-Type: application/json

{
    "name": "Jeans",
    "completed": true
}

###Delete a specific baggages
DELETE {{baseUrl}}/baggages/6a0017f8db270fbb2fb28397

###create a user 
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Faahhh User",
    "email": "user@test4.com",
    "password": "dsfghjghf"
}

### Get all users
GET {{baseUrl}}/users

### Get specific user
GET {{baseUrl}}/users/{{userId}}

###update a specific user
PATCH  {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "name": "Faaaahhhhh",
    "email": ""
}

###delet a specific user
DELETE {{baseUrl}}/users/{{userId}}

###register a user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefgh"
}
